# Generated by Django 5.0.1 on 2024-01-22 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storeuser',
            options={'permissions': [('can_add_storeuser', 'can add srore user'), ('can_update_storeuser', 'can update storeuser'), ('can_delete_storeuser', 'can delete user recored'), ('can_add_edit_delete_role', 'can add/edit/delete role')]},
        ),
    ]
