# Generated by Django 5.0.1 on 2024-01-22 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('dob', models.DateField()),
                ('media_links', models.TextField()),
                ('picture', models.FileField(upload_to='img/authors/')),
                ('awards', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('yoe', models.DateField()),
                ('details', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_type', models.CharField(choices=[('cult', 'CULTURAL'), ('edu', 'EDUCATIONAL'), ('entr', 'ENTERTAINMENT')], max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pages', models.IntegerField()),
                ('desciption', models.TextField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='img/')),
                ('show_pic', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.author')),
            ],
        ),
        migrations.CreateModel(
            name='Complemtry_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_type', models.CharField(max_length=50)),
                ('material', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thumbnail', models.ImageField(upload_to='img/CItems/')),
                ('show_pic', models.TextField()),
                ('description', models.TextField(max_length=500)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.brand')),
            ],
        ),
    ]
